version: '3'
services:
  acadock:
    build: .
    volumes:
      - /sys/fs/cgroup:/host/cgroup:ro
      - /proc:/host/proc:ro
      - /var/run/docker.sock:/host/docker.sock
      - .:/go/src/github.com/Scalingo/acadock-monitoring
    environment:
      HTTP_USERNAME: acadock-monitoring
      HTTP_PASSWORD: p1p0m0l0
      CGROUP_DIR: /host/cgroup
      PROC_DIR: /host/proc
      DOCKER_URL: unix:///host/docker.sock
    command: reflex -r '\.go$$' -s -- sh -c 'go build ./cmd/acadock-monitoring && ./acadock-monitoring'
    privileged: true
    pid: host
    network_mode: host
    ports:
      - "4244:4244"

