services:
  acadock:
    build: .
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /proc:/host/proc:ro
      - /var/run/docker.sock:/host/docker.sock
      - .:/go/src/github.com/Scalingo/acadock-monitoring
    env_file:
      - .env
    command: reflex -r '\.go$$' -s -- sh -c 'go build -buildvcs=false ./cmd/acadock-monitoring && ./acadock-monitoring'
    privileged: true
    pid: host
    network_mode: host
